[[main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 10

[[main]]
  name = "Portfolio"
  pageRef = "/portfolio"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "/projects"
  weight = 30

[[footer]]
  name = "RSS"
  url = "/index.xml"
  weight = 10

[[footer]]
  name = "Email"
  url = "mailto:mianbudulla@protonmail.com"
  weight = 20
